spring:
  redis:
    nodes:
      - localhost:7000
      - localhost:7001
      - localhost:7002
      - localhost:7003
      - localhost:7004
      - localhost:7005
  pool:
    max-idle: 20
    min-idle: 5
    max-active: 20
    max-wait: 1000