#mysql
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flamingo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    user:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/flamingo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456